In [19]:
import torch

In [20]:
x = torch.rand(5,3)
x

tensor([[0.8241, 0.9623, 0.8265],
        [0.8875, 0.6775, 0.0678],
        [0.8438, 0.5565, 0.0824],
        [0.7778, 0.7368, 0.5326],
        [0.6096, 0.5767, 0.5788]])

In [21]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [22]:
x = torch.randn_like(x,dtype=torch.float)
x

tensor([[-1.1167,  0.1029,  0.5996],
        [-1.2067,  1.4284, -1.0661],
        [-0.0320, -0.3634,  1.4178],
        [ 0.2564, -1.0210, -2.3204],
        [-0.0476, -0.2605, -0.1166]])

In [23]:
x.size()

torch.Size([5, 3])

In [24]:
y = torch.rand(5,3)

In [25]:
torch.add(x,y)

tensor([[-0.8348,  0.5407,  0.6893],
        [-0.9977,  1.4544, -0.6345],
        [ 0.7664, -0.3510,  2.3684],
        [ 0.4159, -0.4354, -1.6096],
        [ 0.0588, -0.1941,  0.5014]])

In [26]:
result = torch.empty(5,3)
torch.add(x,y,out = result)

tensor([[-0.8348,  0.5407,  0.6893],
        [-0.9977,  1.4544, -0.6345],
        [ 0.7664, -0.3510,  2.3684],
        [ 0.4159, -0.4354, -1.6096],
        [ 0.0588, -0.1941,  0.5014]])

In [27]:
x,x[:,1]

(tensor([[-1.1167,  0.1029,  0.5996],
         [-1.2067,  1.4284, -1.0661],
         [-0.0320, -0.3634,  1.4178],
         [ 0.2564, -1.0210, -2.3204],
         [-0.0476, -0.2605, -0.1166]]),
 tensor([ 0.1029,  1.4284, -0.3634, -1.0210, -0.2605]))

In [28]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)
x.size(),y.size(),z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [29]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.5160])
0.5160175561904907


In [30]:
import numpy as np

In [31]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [32]:
b=a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [33]:
a.add_(1)
a,b

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [34]:
a = np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
a,b

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))

In [35]:
x = torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [36]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [37]:
y.grad_fn

In [42]:
z = y*y*3
out = torch.mean(z)
z,out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [46]:
a = torch.randn(2,2)
print(a)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

tensor([[-0.6831,  1.5310],
        [-0.5836,  0.4117]])
False
True
