In [32]:
import torch

In [33]:
x = torch.rand(5,3)
x

tensor([[0.5086, 0.6712, 0.2182],
        [0.2869, 0.1116, 0.6412],
        [0.7747, 0.2139, 0.9987],
        [0.6184, 0.0552, 0.8558],
        [0.7774, 0.4845, 0.1786]])

In [34]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [35]:
x = torch.randn_like(x,dtype=torch.float)
x

tensor([[ 5.1507e-01, -1.7500e-01,  5.8532e-01],
        [ 6.2175e-01, -1.8379e+00, -1.6378e+00],
        [ 8.3396e-01, -3.9362e-01,  1.4833e+00],
        [ 5.6812e-01, -8.8934e-01, -2.5676e-01],
        [ 3.7252e-04, -6.5226e-01,  6.4035e-01]])

In [36]:
x.size()

torch.Size([5, 3])

In [37]:
y = torch.rand(5,3)

In [38]:
x+y

tensor([[ 1.4324,  0.0373,  1.2560],
        [ 0.7017, -1.3430, -0.7990],
        [ 1.1145, -0.0986,  1.8787],
        [ 1.3185,  0.0127,  0.6840],
        [ 0.5006, -0.4732,  0.6786]])

In [8]:
result = torch.empty(5,3)
torch.add(x,y,out = result)

tensor([[ 0.4418, -0.2572, -0.4411],
        [-0.1937,  1.1763,  0.2399],
        [ 0.5064,  1.7101,  0.7597],
        [-0.7892,  0.2150,  2.6937],
        [-0.1479,  1.2221, -1.0786]])

In [9]:
x,x[:,1]

(tensor([[ 0.2438, -0.9911, -0.9113],
         [-0.3850,  1.0455, -0.0283],
         [ 0.4469,  0.7837,  0.3217],
         [-0.8918, -0.4122,  2.1844],
         [-0.3086,  1.0724, -1.2656]]),
 tensor([-0.9911,  1.0455,  0.7837, -0.4122,  1.0724]))

In [10]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)
x.size(),y.size(),z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [11]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.2213])
0.22125887870788574


In [12]:
import numpy as np

In [13]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [14]:
b=a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [15]:
a.add_(1)
a,b

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [16]:
a = np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
a,b

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))

In [17]:
x = torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [18]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [19]:
y.grad_fn

In [20]:
z = y*y*3
out = torch.mean(z)
z,out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [21]:
a = torch.randn(2,2)
print(a)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

tensor([[ 0.1981, -0.7361],
        [ 0.5300,  0.1215]])
False
True
