In [2]:
import numpy as np
import torch

In [15]:
np_data = np.arange(6).reshape(2,3)
torch_data = torch.from_numpy(np_data)
res = torch_data.numpy()
print(
    "\n",np_data,
    "\n",torch_data,
    "\n",res
)


 [[0 1 2]
 [3 4 5]] 
 tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32) 
 [[0 1 2]
 [3 4 5]]


In [22]:
data = [[1,2],[3,4]]
torch_data = torch.Tensor(data)
print(np.matmul(data,data))
print(torch.mm(torch_data,torch_data))

[[ 7 10]
 [15 22]]
tensor([[ 7., 10.],
        [15., 22.]])
